<?php
return array (
  9 => 
  array (
    'catid' => '9',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '9',
    'catname' => '王牌',
    'style' => '',
    'image' => 'http://localhost/mobile/uploadfile/images/UI.png',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'UI',
    'url' => 'http://localhost/mobile/index.php?m=content&c=index&a=lists&catid=9',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list - about2","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '9',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'wangpai',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  10 => 
  array (
    'catid' => '10',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '10',
    'catname' => '金牌',
    'style' => '',
    'image' => 'http://localhost/mobile/uploadfile/images/Layer 9.png',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'Web',
    'url' => 'http://localhost/mobile/index.php?m=content&c=index&a=lists&catid=10',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list - about","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '10',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'jinpai',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  11 => 
  array (
    'catid' => '11',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '11',
    'catname' => '精英',
    'style' => '',
    'image' => 'http://localhost/mobile/uploadfile/images/Layer 7.png',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'PHP',
    'url' => 'http://localhost/mobile/index.php?m=content&c=index&a=lists&catid=11',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list - about3","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '11',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'jingying',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  12 => 
  array (
    'catid' => '12',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '12,27,28,29',
    'catname' => '师资团队',
    'style' => '',
    'image' => 'http://localhost/mobile/uploadfile/images/teacher.png',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'teacher',
    'url' => 'http://localhost/mobile/index.php?m=content&c=index&a=lists&catid=12',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category-teacher","list_template":"list-teacher","show_template":"show - issue","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '12',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'shizituandui',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  13 => 
  array (
    'catid' => '13',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '13',
    'catname' => '高新学员',
    'style' => '',
    'image' => 'http://localhost/mobile/uploadfile/images/Layer 3.png',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'students',
    'url' => 'http://localhost/mobile/index.php?m=content&c=index&a=lists&catid=13',
    'items' => '4',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list - students","show_template":"show-teacher","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '13',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'gaoxinxueyuan',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  14 => 
  array (
    'catid' => '14',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '14',
    'catname' => '热门问题',
    'style' => '',
    'image' => 'http://localhost/mobile/uploadfile/images/Layer 2.png',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'issue',
    'url' => 'http://localhost/mobile/index.php?m=content&c=index&a=lists&catid=14',
    'items' => '4',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list - issue","show_template":"show - issue","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '14',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'remenwenti',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  15 => 
  array (
    'catid' => '15',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '15',
    'catname' => '媒体报道',
    'style' => '',
    'image' => 'http://localhost/mobile/uploadfile/images/Layer 1.png',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'reports',
    'url' => 'http://localhost/mobile/index.php?m=content&c=index&a=lists&catid=15',
    'items' => '3',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list - media","show_template":"show - media","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '15',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'meitibaodao',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  16 => 
  array (
    'catid' => '16',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '16',
    'catname' => '关于我们',
    'style' => '',
    'image' => 'http://localhost/mobile/uploadfile/images/Capa 1.png',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'Aboot',
    'url' => 'http://localhost/mobile/index.php?m=content&c=index&a=lists&catid=16',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list - about1","show_template":"show - about1","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '16',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'guanyuwomen',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  27 => 
  array (
    'catid' => '27',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '12',
    'arrparentid' => '0,12',
    'child' => '0',
    'arrchildid' => '27',
    'catname' => '王牌讲师',
    'style' => '',
    'image' => 'http://localhost/mobile/uploadfile/images/teacher.png',
    'description' => '',
    'parentdir' => 'teacher/',
    'catdir' => 'UI_',
    'url' => 'http://localhost/mobile/index.php?m=content&c=index&a=lists&catid=27',
    'items' => '4',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category-teacher","list_template":"list-teacher","show_template":"show-teacher","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '27',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'wangpaijiangshi',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  28 => 
  array (
    'catid' => '28',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '12',
    'arrparentid' => '0,12',
    'child' => '0',
    'arrchildid' => '28',
    'catname' => '金牌讲师',
    'style' => '',
    'image' => 'http://localhost/mobile/uploadfile/images/teacher.png',
    'description' => '',
    'parentdir' => 'teacher/',
    'catdir' => 'Web_',
    'url' => 'http://localhost/mobile/index.php?m=content&c=index&a=lists&catid=28',
    'items' => '2',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category-teacher","list_template":"list-teacher","show_template":"show-teacher","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '28',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'jinpaijiangshi',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  29 => 
  array (
    'catid' => '29',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '12',
    'arrparentid' => '0,12',
    'child' => '0',
    'arrchildid' => '29',
    'catname' => '精英讲师',
    'style' => '',
    'image' => 'http://localhost/mobile/uploadfile/images/teacher.png',
    'description' => '',
    'parentdir' => 'teacher/',
    'catdir' => 'PHP_',
    'url' => 'http://localhost/mobile/index.php?m=content&c=index&a=lists&catid=29',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category-teacher","list_template":"list-teacher","show_template":"show-teacher","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '29',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'jingyingjiangshi',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  32 => 
  array (
    'catid' => '32',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '32',
    'catname' => '助学贷款',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'zhuxe',
    'url' => 'http://localhost/mobile/index.php?m=content&c=index&a=lists&catid=32',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show-daikuan","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '32',
    'ismenu' => '0',
    'sethtml' => '0',
    'letter' => 'zhuxuedaikuan',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  37 => 
  array (
    'catid' => '37',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '37',
    'catname' => '免费体检',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'tijain',
    'url' => 'http://localhost/mobile/index.php?m=content&c=index&a=lists&catid=37',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show - tijian","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '37',
    'ismenu' => '0',
    'sethtml' => '0',
    'letter' => 'mianfeitijian',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>